name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y freeglut3-dev
    - name: Build
      run: g++ homer.cpp -o homer -lGL -lglut\
    - name: Give execution permission
      run: chmod +x homer
    - uses: actions/upload-artifact@v2
      with:
        name: app
        path: homer
